I need to create a dataset that will include three columns and for each column five values

The three columns will be: users, country, rating describing several users (dfifferent names for example, each user from a different country and each user rates his/her country from 1 to 10 (1 I do not like this country , 10 I adore this country)

# First you need to decide the libraries you need to import and use 

pandas #dataframes and work with dataframes 
numpy #deal with numbers, equations anf formulas
matplotlib # to visualize

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data = {
    "users": ["Bob", "John", "Mike", "Kelly", "Sofia"],
    "country" : ["Greece", "Albania", "France", "USA", "UK"],
    "rating" : [5, 7, 6, 8, 8]
}

In [7]:
df = pd.DataFrame(data)
#print(df)
df

   users  country  rating
0    Bob   Greece       5
1   John  Albania       7
2   Mike   France       6
3  Kelly      USA       8
4  Sofia       UK       8

In [8]:
df.dtypes # will print features and their data types

users      object
country    object
rating      int64
dtype: object

# Mean Median Standard Deviation

In [ ]:
df["rating"].mean()
df["rating"].median()
df["rating"].std()

1.3038404810405297

In [12]:
df["rating"].mean()

6.8

In [14]:
df["rating"].median()

7.0

In [17]:
# load the csv
df = pd.read_csv("House Price Prediction Dataset.csv")
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [18]:
df.dtypes

Id            int64
Area          int64
Bedrooms      int64
Bathrooms     int64
Floors        int64
YearBuilt     int64
Location     object
Condition    object
Garage       object
Price         int64
dtype: object

# Explaratory Data Analysis (EDA) BASICS 
--> TARGET IS TO PREDICT HOUSE PRICES
--> USE OF HISTORICAL DATA
--> REGRESSION (LINEAR REGRESSION)

In [20]:
# Calculate the median of Price column

df["Price"].median()

539254.0

In [21]:
df["Price"].mean()

537676.855

In [23]:
df["Price"].std()

276428.84571913956

In [25]:
df.describe()
#Quick overview

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [27]:
# missing values

df.isnull()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False,False

In [28]:
## missing = df.isna().mean().sort_values(ascending=False) # if you have missing values

## Split the dataset in Train/Test

# target (column): Price (2000) 
# features/variables: YearBuilt (2000)  

# X = df["YearBuilt"]

In [37]:
from sklearn.model_selection import train_test_split


X = df[["YearBuilt","Floors"]]
y = df["Price"]

# y = df.drop(["column1", "column2" etc])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print("Train:", X_train.shape, "Test:", X_test.shape)

Train: (1600, 2) Test: (400, 2)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
# calling the model  
model = LinearRegression()
 # fitting the model 
model.fit(X_train, y_train)

# to calculated the predicted price
y_pred = model.predict(X_test)
y_pred[:10]

array([520734.65504014, 517767.33547359, 562193.46545556, 539444.63443173,
       542411.95399828, 542082.25182421, 563924.40186938, 560544.95458526,
       543978.03932506, 561286.78447689])

In [43]:
# plot y_pred vs y_actual 
# different color, line type to differentiate the actual and the predicted

# calculate the error between the actual and the predicted
# can you trust this model for housepricing? yes/no and why?